# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: 29ce590afc552b5e1d1d376e316e961c77455ec7bd8624686249898c3c15574c6a673f3e76a980a708b1f348c5f7777c4ddb6579fea3622b8907e4fd98abe574

test:
  secret_key_base: 0bb4d6fdebe1d11126ed3cc522c5972248741facf1dd1eb02abb03a8b94c83b0c480012b634734163c44b714b3ce589fd6795ef5191ef673babf470b9bfa0974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
